### ISSUE TITLE
SQL Server connection is not working

### ISSUE THREAD

**Issue by BigDi** [tomaszsluszniak/newman-reporter-sql#1]
Use SQL Server 2016 with sa user/password. TCP port 1433 is activated. Datebase newman_reports is created. 
When I execute the newman collection then I got the followed error:

`newman run C:\postman\Collection.json -e C:\postman\Environment.json -r sql,cli --reporter-sql-dialect mssql --reporter-sql-server mysqlserver --reporter-sql-port 1433 --reporter-sql-name newman_reports --reporter-sql-table api_results --reporter-sql-username sa --reporter-sql-password XXXXXXX --reporter-sql-debug true`

` ERROR: While creating SQL connection:  TypeError: Cannot read property 'length' of undefined
    at Table._initValues (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman-reporter-sql\node_modules\sequelize\lib\model.js:140:49)
    at new Model (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman-reporter-sql\node_modules\sequelize\lib\model.js:118:10)
    at new Table (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman-reporter-sql\src\SQLReporter.js:3:1)
    at Function.build (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman-reporter-sql\node_modules\sequelize\lib\model.js:2157:12)
    at Function.create (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman-reporter-sql\node_modules\sequelize\lib\model.js:2207:23)
    at SQLReporter.item (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman-reporter-sql\src\SQLReporter.js:182:19)
    at EventEmitter.<anonymous> (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman-reporter-sql\src\SQLReporter.js:23:105)
    at EventEmitter.emit (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman\node_modules\eventemitter3\index.js:203:33)
    at Function.callbacks.<computed> [as item] (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:211:34)
    at PostmanCollectionRun.<anonymous> (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\item.command.js:251:47)
    at apply (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:475:27)
    at C:\Users\dsa\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:9499:36
    at C:\Users\dsa\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:4901:15
    at Function.<anonymous> (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:9498:7)
    at apply (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:476:27)
    at Function.invokeMap (C:\Users\dsa\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:6585:16)`

**Comment by tomaszsluszniak** [comment]
@BigDi Please check the 1.0.5 version

**Comment by BigDi** [comment]
I tested version 1.0.5 but issue still exists. 
`[-] ERROR: While creating SQL connection:  TypeError: Cannot read property 'length' of undefined
    at Table._initValues (C:\Users\admin\AppData\Roaming\npm\node_modules\newman-reporter-sql\node_modules\sequelize\lib\model.js:140:49)
    at new Model (C:\Users\admin\AppData\Roaming\npm\node_modules\newman-reporter-sql\node_modules\sequelize\lib\model.js:118:10)
    at new Table (C:\Users\admin\AppData\Roaming\npm\node_modules\newman-reporter-sql\src\SQLReporter.js:3:1)
    at Function.build (C:\Users\admin\AppData\Roaming\npm\node_modules\newman-reporter-sql\node_modules\sequelize\lib\model.js:2157:12)
    at Function.create (C:\Users\admin\AppData\Roaming\npm\node_modules\newman-reporter-sql\node_modules\sequelize\lib\model.js:2207:23)
    at SQLReporter.item (C:\Users\admin\AppData\Roaming\npm\node_modules\newman-reporter-sql\src\SQLReporter.js:183:19)
    at EventEmitter.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\newman-reporter-sql\src\SQLReporter.js:23:105)
    at EventEmitter.emit (C:\Users\admin\AppData\Roaming\npm\node_modules\newman\node_modules\eventemitter3\index.js:203:33)
    at Function.callbacks.<computed> [as item] (C:\Users\admin\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:211:34)
    at PostmanCollectionRun.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\item.command.js:251:47)
    at apply (C:\Users\admin\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:475:27)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:9499:36
    at C:\Users\admin\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:4901:15
    at Function.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:9498:7)
    at apply (C:\Users\admin\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:476:27)
    at Function.invokeMap (C:\Users\admin\AppData\Roaming\npm\node_modules\newman\node_modules\lodash\lodash.js:6585:16)`

**Comment by tomaszsluszniak** [comment]
Stupid question, but.. do you have the Tedious package installed (https://www.npmjs.com/package/tedious)?

**Comment by BigDi** [comment]
Yes, I have. I also tried to debug it. It seems that the connection is made because I get returned the version number of SQL server. But then it seems that the requested parameter block is smaller than expected.

**Comment by tomaszsluszniak** [comment]
I managed to fix the issue. Please check the 1.0.6 version. It's already published.

**Comment by BigDi** [comment]
It works now! Many thanks!
